networks:
  p2p:
    driver: bridge

services:
  rate-limiter-bootstrap:
    build: .
    networks:
      - p2p
    volumes:
      - ./data:/data

  rate-limiter:
    build: .
    networks:
      - p2p
    environment:
      - BOOTSTRAP_PEER=/ip4/172.18.0.2/tcp/46793/p2p/12D3KooWRJncgJ2CCDvha1CLDTdsqDHXc1dR9FsauKXbDmJM3mfW
    deploy:
      replicas: 3
    volumes:
      - ./data:/data

  nginx:
    image: nginx:latest
    networks:
      - p2p
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro